## Gauss Elimination

In [10]:
import numpy as np


Defining Ax=B

In [11]:
# a =np.array([[2.,1.,4.,1.],[3.,4.,-1.,-1.],[1.,-4.,1.,5.],[2.,-2.,1.,3.]])
# b= np.array([-4.,3.,9.,7.])
# x = np.zeros(4,float)
# print('A is\n',a)
# print('B is\n',b)
# # print(a[3,3])

In [56]:
def gauss_elimination(a,b):
    n = len(b)
    x = np.zeros(n,float)

    for i in range(n):

        temp = a[i,i]
        a[i,:]/= temp
        b[i]/= temp
       
        for j in range(i+1,n):

            temp = a[j,i]
            a[j,:]-=temp*a[i,:]
            b[j]-=temp*b[i]
        print(a)
        print(b)
    
    for i in range(n-1,-1,-1):

        x[i] = b[i]
        
        for j in range(n-1,i,-1):
 
            x[i]-=a[i][j]*x[j]

    return x

In [58]:
a =np.array([[2.,1.,4.,1.],[3.,4.,-1.,-1.],[1.,-4.,1.,5.],[2.,-2.,1.,3.]])
b= np.array([-4.,3.,9.,7.])
x = gauss_elimination(a,b)
print("The result is:\n",x)

[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
[-2.  9. 11. 11.]
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.    0.  -11.4  -1. ]]
[-2.   3.6 27.2 21.8]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [ 0.   0.   0.  -1. ]]
[-2.   3.6 -2.  -1. ]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
[-2.   3.6 -2.   1. ]
The result is:
 [ 2. -1. -2.  1.]


### Using predefined function

In [5]:
from numpy.linalg import solve
X =solve(a,b)
print(X)


[ 2. -1. -2.  1.]
