### Gauss Seidel
- here we will right a code for gauss seidel.

Given the three equation:

4x + y + 2z = 4<br>
3x + 5y + z = 7<br>
x + y + 3z = 3<br>
First we assume that the solution of given equation is

(0,0,0)
Then first we put value of y and z in equation 1 and get value of x and update the value of x as

(x1,0,0)
Now, putting the updated value of x that is x1 and z=0 in equation 2 to get y1 and then updating our solution as

(x1,y1,0)
Then, at last putting x1 and y1 in equation 3 to get z1 and updating our solution as

(x1,y1,z1)

In [17]:
import numpy as np
import numpy.linalg as npl


In [66]:
def gauss_seidel(a,b,x):
    n = len(b)
    iteration = 1e4
    tolerance = 1e-8 
    t=0
    print(a)
    print(b)
    while(t< iteration):
        xold=np.copy(x)
        for i in range(n):
            
            b1 = b[i]
            for j in range(n):
                if i!=j:
                    b1-=a[i,j]*x[j]
            x[i]=b1/a[i,i]
        test=abs(npl.norm(x)-npl.norm(xold)) #teke delta norm for an idication of how close we are
        if test < tolerance:
            print("hello")
            print('Max tolerance reached')
            break
        t+=1
    print('number of itteration:',t)
    
    return x
            
        

In [67]:
a=np.array([[4.,-1.,1.],[-1.,4.,-2.],[1.,-2.,4.]])
b=np.array([12.,-1.,5.])
x = np.zeros(len(b))
gauss_seidel(a,b,x)


[[ 4. -1.  1.]
 [-1.  4. -2.]
 [ 1. -2.  4.]]
[12. -1.  5.]
hello
Max tolerance reached
number of itteration: 12


array([3., 1., 1.])